@BirdWare_HostAddress = https://birdware.dk

###
GET {{BirdWare_HostAddress}}/api/forskel/iaar
Accept: application/json

###
GET {{BirdWare_HostAddress}}/api/forskel/sidsteaar
Accept: application/json

###
GET {{BirdWare_HostAddress}}/api/fugletur/foreslaaArter

###
GET {{BirdWare_HostAddress}}/api/fugletur/3101/analyse
